---
title: "vis_2"
author: "My An Huynh"
date: "2024-10-01"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

```
 
Import weather data 
 
```{r weather}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

Making the first plot

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  labs(
    title = "Temperature Scatterplot",
    x = "Minimum Temperature (C)",
    y = "Maximum Temperature (C)",
    color = "Location",
    caption = "Weather data taken from rnoaa package for 3 stations"
  )

```

Scales -- start with x and y and then do color.

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  labs(
    title = "Temperature Scatterplot",
    x = "Minimum Temperature (C)",
    y = "Maximum Temperature (C)",
    color = "Location",
    caption = "Weather data taken from rnoaa package for 3 stations"
  ) + 
  scale_x_continuous(
    breaks = c(-15, 0, 20),
    labels = c("-15C", "0C", "20C")
) +
  scale_y_continuous(
    limits = c(0,30), 
    transform = "sqrt"
  )

```

Look at color. Use the viridis package for built in color palette. 

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  labs(
    title = "Temperature Scatterplot",
    x = "Minimum Temperature (C)",
    y = "Maximum Temperature (C)",
    color = "Location",
    caption = "Weather data taken from rnoaa package for 3 stations"
  ) + 
  scale_color_hue(h = c(10,400)) +
  viridis::scale_color_viridis(discrete = TRUE)
```

